-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema Clinica
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema Clinica
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `Clinica` DEFAULT CHARACTER SET utf8 ;
USE `Clinica` ;

-- -----------------------------------------------------
-- Table `Clinica`.`PACIENTE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`PACIENTE` (
  `idPACIENTE` INT NOT NULL AUTO_INCREMENT,
  `CPF` VARCHAR(11) NOT NULL,
  `NOME` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `SENHA` VARCHAR(45) NOT NULL,
  `N_PLANO` INT NULL,
  PRIMARY KEY (`idPACIENTE`),
  UNIQUE INDEX `CPF_UNIQUE` (`CPF` ASC) VISIBLE,
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE,
  UNIQUE INDEX `ID_PLANO_UNIQUE` (`N_PLANO` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica`.`TELEFONE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`TELEFONE` (
  `NUM_TELEFONE` INT NOT NULL,
  `PACIENTE_idPACIENTE` INT NOT NULL,
  UNIQUE INDEX `NUM_TELEFONE_UNIQUE` (`NUM_TELEFONE` ASC) VISIBLE,
  PRIMARY KEY (`PACIENTE_idPACIENTE`, `NUM_TELEFONE`),
  CONSTRAINT `fk_TELEFONE_PACIENTE`
    FOREIGN KEY (`PACIENTE_idPACIENTE`)
    REFERENCES `Clinica`.`PACIENTE` (`idPACIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica`.`ENDERECO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`ENDERECO` (
  `CEP` INT NOT NULL,
  `MUNICIPIO` VARCHAR(45) NOT NULL,
  `BAIRRO` VARCHAR(45) NOT NULL,
  `UF` CHAR(2) NOT NULL,
  `LOGRADOURO` VARCHAR(50) NOT NULL,
  `NUMERO` INT NOT NULL,
  `PACIENTE_idPACIENTE` INT NOT NULL,
  PRIMARY KEY (`CEP`, `PACIENTE_idPACIENTE`),
  INDEX `fk_ENDERECO_PACIENTE1_idx` (`PACIENTE_idPACIENTE` ASC) VISIBLE,
  CONSTRAINT `fk_ENDERECO_PACIENTE1`
    FOREIGN KEY (`PACIENTE_idPACIENTE`)
    REFERENCES `Clinica`.`PACIENTE` (`idPACIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica`.`MEDICO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`MEDICO` (
  `ID_MEDICO` INT NOT NULL AUTO_INCREMENT,
  `MEDICO` VARCHAR(50) NOT NULL,
  `EMAIL` VARCHAR(50) NOT NULL,
  `CRM` INT NOT NULL,
  PRIMARY KEY (`ID_MEDICO`),
  UNIQUE INDEX `EMAIL_UNIQUE` (`EMAIL` ASC) VISIBLE,
  UNIQUE INDEX `CRM_UNIQUE` (`CRM` ASC) VISIBLE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica`.`ESPECIALIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`ESPECIALIDADE` (
  `ID_ESPECIALIDADE` INT NOT NULL,
  `DESC_ESPEC` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`ID_ESPECIALIDADE`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica`.`MEDICO_ESPECIALIDADE`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`MEDICO_ESPECIALIDADE` (
  `MEDICO_ID_MEDICO` INT NOT NULL,
  `ESPECIALIDADE_ID_ESPECIALIDADE` INT NOT NULL,
  PRIMARY KEY (`MEDICO_ID_MEDICO`, `ESPECIALIDADE_ID_ESPECIALIDADE`),
  INDEX `fk_MEDICO_has_ESPECIALIDADE_ESPECIALIDADE1_idx` (`ESPECIALIDADE_ID_ESPECIALIDADE` ASC) VISIBLE,
  INDEX `fk_MEDICO_has_ESPECIALIDADE_MEDICO1_idx` (`MEDICO_ID_MEDICO` ASC) VISIBLE,
  CONSTRAINT `fk_MEDICO_has_ESPECIALIDADE_MEDICO1`
    FOREIGN KEY (`MEDICO_ID_MEDICO`)
    REFERENCES `Clinica`.`MEDICO` (`ID_MEDICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_MEDICO_has_ESPECIALIDADE_ESPECIALIDADE1`
    FOREIGN KEY (`ESPECIALIDADE_ID_ESPECIALIDADE`)
    REFERENCES `Clinica`.`ESPECIALIDADE` (`ID_ESPECIALIDADE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica`.`HORARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`HORARIO` (
  `ID_AGENDA` INT NOT NULL AUTO_INCREMENT,
  `DATA_HORA` DATETIME NOT NULL,
  PRIMARY KEY (`ID_AGENDA`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica`.`MEDICO_HORARIO`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`MEDICO_HORARIO` (
  `HORARIO_ID_AGENDA` INT NOT NULL,
  `MEDICO_ID_MEDICO` INT NOT NULL,
  PRIMARY KEY (`HORARIO_ID_AGENDA`, `MEDICO_ID_MEDICO`),
  INDEX `fk_HORARIO_has_MEDICO_MEDICO1_idx` (`MEDICO_ID_MEDICO` ASC) VISIBLE,
  INDEX `fk_HORARIO_has_MEDICO_HORARIO1_idx` (`HORARIO_ID_AGENDA` ASC) VISIBLE,
  CONSTRAINT `fk_HORARIO_has_MEDICO_HORARIO1`
    FOREIGN KEY (`HORARIO_ID_AGENDA`)
    REFERENCES `Clinica`.`HORARIO` (`ID_AGENDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_HORARIO_has_MEDICO_MEDICO1`
    FOREIGN KEY (`MEDICO_ID_MEDICO`)
    REFERENCES `Clinica`.`MEDICO` (`ID_MEDICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `Clinica`.`CONSULTA`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `Clinica`.`CONSULTA` (
  `PACIENTE_idPACIENTE` INT NOT NULL,
  `MEDICO_ID_MEDICO` INT NOT NULL,
  `HORARIO_ID_AGENDA` INT NOT NULL,
  PRIMARY KEY (`PACIENTE_idPACIENTE`, `MEDICO_ID_MEDICO`, `HORARIO_ID_AGENDA`),
  INDEX `fk_PACIENTE_has_MEDICO_MEDICO1_idx` (`MEDICO_ID_MEDICO` ASC) VISIBLE,
  INDEX `fk_PACIENTE_has_MEDICO_PACIENTE1_idx` (`PACIENTE_idPACIENTE` ASC) VISIBLE,
  INDEX `fk_CONSULTA_HORARIO1_idx` (`HORARIO_ID_AGENDA` ASC) VISIBLE,
  CONSTRAINT `fk_PACIENTE_has_MEDICO_PACIENTE1`
    FOREIGN KEY (`PACIENTE_idPACIENTE`)
    REFERENCES `Clinica`.`PACIENTE` (`idPACIENTE`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_PACIENTE_has_MEDICO_MEDICO1`
    FOREIGN KEY (`MEDICO_ID_MEDICO`)
    REFERENCES `Clinica`.`MEDICO` (`ID_MEDICO`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_CONSULTA_HORARIO1`
    FOREIGN KEY (`HORARIO_ID_AGENDA`)
    REFERENCES `Clinica`.`HORARIO` (`ID_AGENDA`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
